EXCEPTION HANDLING

Syntax Errors 

In [1]:
if 10>5:
    print("hi")
else:
    print("bye")

hi


In [2]:
print "Hi"

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (2419407535.py, line 1)

In [4]:
if true:
print("Welcome")

IndentationError: expected an indented block after 'if' statement on line 1 (1672831184.py, line 2)

RUN TIME ERROR

In [5]:
a=10
b=0
print(a/b)

ZeroDivisionError: division by zero

In [6]:
lst=10
print(len(lst))

TypeError: object of type 'int' has no len()

In [7]:
num=int(input("Enter num:"))
print(num)

Enter num: 4


4


In [8]:
num=int(input("Enter num:"))
print(num)

Enter num: @


ValueError: invalid literal for int() with base 10: '@'

In [9]:
print("age" + 9)

TypeError: can only concatenate str (not "int") to str

In [10]:
lst=['apple',250,'orange']
lst[5]

IndexError: list index out of range

In [12]:
d={'name':'Monu','branch':'data science'}
d['branch']
d['city']

KeyError: 'city'

In [13]:
lst=[10,20,30]
lst.append(40)
lst

[10, 20, 30, 40]

In [15]:
tup=(10,20,30)
tup.append(40)
tup

AttributeError: 'tuple' object has no attribute 'append'

In [16]:
open("Interview.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'Interview.txt'

In [17]:
try:
    num1=int(input("Enter num1:"))
    num2=int(input("Enter num2:"))
    result=num1/num2
    print("Result:",result)
except exception as e:
    print("error:Can't divide by zero")
else:
    print("Hi")
    print("Welcome")
finally:
    print("I am Lucky,I execute always.Program end!")
    

Enter num1: 5
Enter num2: 2


Result: 2.5
Hi
Welcome
I am Lucky,I execute always.Program end!


In [19]:
try:
    num1=int(input("Enter num1:"))
    num2=int(input("Enter num2:"))
    result=num1/num2
    print("Result:",result)
except Exception as e:
    print("error:Can't divide by zero")
else:
    print("Hi")
    print("Welcome")
finally:
    print("I am Lucky,I execute always.Program end!")
    

Enter num1: 4
Enter num2: 0


error:Can't divide by zero
I am Lucky,I execute always.Program end!


In [21]:
a=7
b=0
print(a/b)
print("Hi")

ZeroDivisionError: division by zero

In [23]:
try:
    a=7
    b=0
    print(a/b)
except ZeroDivisionError:
    prin("Don't divide any num with zero")
print("Welcome")
print("H w r u?")


NameError: name 'prin' is not defined

In [25]:
try:
    print("a"+2)
except TypeError:
    print("Error occured check your pgm once")
print(4+6)
print("hi")

Error occured check your pgm once
10
hi


In [26]:
print("a" + 2)

TypeError: can only concatenate str (not "int") to str

In [29]:
try:
    lst=[10,'apple','blue']
print(lst[8])

SyntaxError: expected 'except' or 'finally' block (2481793269.py, line 3)

In [30]:
try:
    lst=[10,'apple','blue']
    print(lst[8])
except ZeroDivisionError:
    print("Error:Can't divby zero")
except IndexError:
    print("Error:Check index once!")
except ValueError:
    print("Error:Check input once!")
except TypeError:
    print("Error:Dude check datatype once!")

Error:Check index once!



NUMPY VS LIST

In [1]:
arr=[10,20,30]
arr


[10, 20, 30]

In [2]:
arr[0]

10

In [3]:
import numpy as np
arr1=np.array([10,20,30])
arr1

array([10, 20, 30])

In [5]:
lst=[100,200]
print(lst*2)

[100, 200, 100, 200]


In [6]:
print("Numpy array:",arr1)
print(arr1*2)

Numpy array: [10 20 30]
[20 40 60]


In [8]:
print(np.arange(1,21,1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [9]:
print(np.arange(2,21,2))

[ 2  4  6  8 10 12 14 16 18 20]


In [11]:
print(len(np.arange(2,21,2)))

10


In [12]:
print("Dimension:",np.arange(2,21,2).ndim)

Dimension: 1


In [14]:
two=np.array([[10,20,30],[40,50,60]])
print("2D:\n",two)

2D:
 [[10 20 30]
 [40 50 60]]


In [15]:
two.ndim

2

In [16]:
three=np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print("3D:\n",three)

3D:
 [[[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [17]:
three.ndim

3

In [18]:
print("total no of elements(3D):",three.size)

total no of elements(3D): 9


Linspace(start,end,num):Evenly spaced values between start and end(inclusive)

In [19]:
Lin = np.linspace(5,20,4,dtype=int)
print(Lin)

[ 5 10 15 20]


In [20]:
print(np.linspace(3,43,8))

[ 3.          8.71428571 14.42857143 20.14285714 25.85714286 31.57142857
 37.28571429 43.        ]


In [21]:
print(np.eye((3),dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [22]:
print(np.zeros((3,3),dtype=int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
print(np.ones((3,3),dtype=int))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [24]:
print(np.zeros((3,5),dtype=int))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


RANDOM FUNCTION

In [25]:
print(np.random.choice([1,2,3,4,5]))

4


In [26]:
print(np.random.rand())

0.9637601298791076


In [27]:
print(np.random.randn(5))#standard normal

[ 0.34582339 -2.23141644  1.57811208 -0.01902272 -0.26026338]


In [28]:
marks=np.array([55,67,89,95])
marks

array([55, 67, 89, 95])

In [29]:
print("Total Marks:",marks.sum())

Total Marks: 306


In [30]:
print("Min Marks:",marks.min())

Min Marks: 55


In [3]:
import numpy as np
arr1=np.array([10,20,30])
arr1

array([10, 20, 30])

In [4]:
arr1

array([10, 20, 30])

In [5]:
print(arr1*5)

[ 50 100 150]


In [6]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)
print(arr1*arr2)

[5 7 9]
[ 4 10 18]


SLICING AND INDEXING

In [7]:
a=np.array([10,20,30,40])
print(a[-1])
print(a[3])

40
40


In [8]:
print(a[0:2])

[10 20]


In [10]:
b=np.array([[13,15,17],[19,21,23]])
b

array([[13, 15, 17],
       [19, 21, 23]])

In [11]:
print(b[1,1])

21


In [13]:
print(b[0][1:])

[15 17]


STATISTICAL FUNCTIONS

In [15]:
print(b.mean())

18.0


In [16]:
print(b.min())

13


In [18]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]


In [20]:
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[13,15,17],[19,21,23]])
print(np.concatenate((a,b)))

[[10 20 30]
 [40 50 60]
 [13 15 17]
 [19 21 23]]


In [21]:
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[13,15,17],[19,21,23]])
result=np.concatenate((a,b),axis=1)
result

array([[10, 20, 30, 13, 15, 17],
       [40, 50, 60, 19, 21, 23]])

In [22]:
c=np.array([1,2,3,4,5,6])
res=np.split(c,3)
res

[array([1, 2]), array([3, 4]), array([5, 6])]

In [23]:
c=np.array([1,2,3,4,5,6])
res=np.split(c,6)
res

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]

In [24]:
d=np.array([45,23,12,9,3,6])
print(np.sort(d))

[ 3  6  9 12 23 45]


In [25]:
#Min and Max index of an element
d

array([45, 23, 12,  9,  3,  6])

In [26]:
print("Max val index:",np.argmax(d))
print("Min val index:",np.argmin(d))

Max val index: 0
Min val index: 4


BOOLEAN FILTER

In [29]:
print(d)
#val<10
result=d[d<10]
print("val<10:",result)

[45 23 12  9  3  6]
val<10: [9 3 6]


In [30]:
d<10

array([False, False, False,  True,  True,  True])